# this docker compose is only used for local testing at the moment, at some point when a CI/CD is brought in, configurable
# env variables will be used where appropriate and expected (i.e. port numbers, usernames, passwords, db names
version: '3'
# use
# unix-socker: desktop-linux
services:
  mysql-container:
    image: mysql:8.1.0
    environment:
#      MYSQL_USER: test-db-root
#      MYSQL_PASSWORD: test-db-root-pass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-db
    ports:
      - "3308:3306"
#      for mac:
#      - "3306:3306"
    volumes:
      - "./conf/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"
# the section below is just a reminder of what this would look like if there was an app running along with the DB image
#  app:
#    image: asutalo/at-it:latest
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql-container